### ISSUE TITLE
Table header layout

### ISSUE THREAD

**Issue by catacovaciu** [grommet/grommet-ferret#14]
When I open the "Activity" tab for the first time, there is a layout issue for the last 3 column headers(see attached img). Initially they are displayed properly, but then the content of the table is moved abit to the right and this causes the issue. If you click for example on the header or resize the window, the issue dissapears. I also inspected the element and noticed that there is a table(class="table__mirror") that contains only the header, if I delete this element the issue is gone again.
It is reproducible only when the "Activity" tab is open for the first time.
This isue is also reproducible on a local application which uses the index component.

Reproduced on: Chrome 47

![capture](https://cloud.githubusercontent.com/assets/16778876/12476857/d96b75dc-c034-11e5-8958-e3ee02ca7e16.PNG)

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet/pull/364
