### ISSUE TITLE
Cannot load app after following the README

### ISSUE THREAD

**Issue by Draffodx** [grommet/grommet-ferret#19]
I have followed the README instructions to download the code, get the modules and start both the server and the client but when I do so the client stays on the loading screen.

I get the following error in the command line for the client:

> ERROR in ./src/js/index.js
Module not found: Error: Cannot resolve module 'react-intl/lib/locale-data/en' in C:\Users\raffertd\grommet-ferret\src\js
 @ ./src/js/index.js 31:10-50

**Comment by alansouzati** [comment]
Fixed in https://github.com/grommet/grommet-ferret/commit/bfe78abb16bb258c23688035e08897fe051180f7
