### ISSUE TITLE
Application start up issue

### ISSUE THREAD

**Issue by karthicktv** [grommet/grommet-ferret#20]
After the $ npm install, I am able to start the dev env using $ gulp dev ... 
but when I open the browser, I get this error: 

Uncaught SyntaxError: Unexpected token <

Upon inspection, it is reporting the first line in Index.js

![image](https://cloud.githubusercontent.com/assets/8471776/14645219/b33c413a-064c-11e6-90e9-403141ef33a7.png)

My versions are:
Node - v5.10.1
Npm - 3.8.3

Please help!

**Comment by alansouzati** [comment]
can you provide the logs in the command line?

**Comment by alansouzati** [comment]
But first let me fix and move ferret to use grommet-toolbox

**Comment by alansouzati** [comment]
can you try again with the latest ferret?

**Comment by karthicktv** [comment]
Hi Alan, I tried again after your latest change but still the same error.

**Comment by karthicktv** [comment]
I also get this error as there is no dist folder for this project; and when I tried copying the "dist" folder from another project, I get the the error, as above: "Uncaught SyntaxError: Unexpected token <"

Error: ENOENT: no such file or directory, stat '/home/karthick/grommet-ferret/dist/index.html'
   at Error (native)

Hope this gives you more info to correct me what I am doing wrong and help fix. Thanks.

**Comment by bryanjacquot** [comment]
@karthicktv are you still seeing this issue, and if so, how you're trying to run the ferret application?  It appears the index.js file has HTML content which should not be the case.

**Comment by bryanjacquot** [comment]
Closing for now.

**Comment by isurusiri** [comment]
To anyone still struggling with this, build the application and then start. 

`> NODE_ENV=production grommet pack`
`> npm start`
Hope this helps :)
