### ISSUE TITLE
Error: Cannot resolve module 'grommet/components/icons/Clear'

### ISSUE THREAD

**Issue by PhilipAndersonHPE** [grommet/grommet-ferret#21]
Running `gulp dev` from master of grommet-ferret returns an Error:

the output shows 482 components build but one has an error

`[463] ./src/js/components/server-profiles/ServerProfileForm.js 25.9 kB {0} [built] [1 error]`

```
ERROR in ./src/js/components/server-profiles/ServerProfileForm.js
Module not found: Error: Cannot resolve module 'grommet/components/icons/Clear' in /root/grommet/grommet-ferret-master/src/js/components/server-profiles
 @ ./src/js/components/server-profiles/ServerProfileForm.js 63:13-54
```

Following this the app starts but only the grommet logo is displayed.

I checked and sure enough grommet/components/icons/Clear does not exist  .... So I modified **ServerProfileForm.js** to point to a file that does exist, restarted with `gulp dev` and the app loaded fine i.e. all 482 components including:

`  [463] ./src/js/components/server-profiles/ServerProfileForm.js 25.9 kB {0} [built]`

The question is should the file **grommet/components/icons/Clear** exist, am I missing a dependency? Or has it been replaced and **/src/js/components/server-profiles/ServerProfileForm.js** needs updating?

My setup:

**OS:**       Centos 7.1 
**Node:**    6.0.0
**NPM:**     3.8.6
**Python**:   2.7.5
**gulp**: CLI version 3.9.1
**grommet** 3.8.6

**Comment by alansouzati** [comment]
`import CloseIcon from 'grommet/components/icons/Clear';` has been deprecated and we ended up forgetting to remove from Ferret when we release 0.6.2, sorry about that.

Would you mind sending a Pull Request to replace:

`import CloseIcon from 'grommet/components/icons/Clear';`

by

`import CloseIcon from 'grommet/components/icons/base/Close';`

I'm fine fixing it myself, but it would a great contribution from you 😄

**Comment by PhilipAndersonHPE** [comment]
Fix verified on latest master, closing issue
