### ISSUE TITLE
Duplicate [path] variable in server.js

### ISSUE THREAD

**Issue by iamnote** [grommet/grommet-ferret#25]
There were 2 var path defined in the server.js.

`var path = require('path');

var PORT = process.env.PORT || 8010;

var app = express();

app.use(ddos.express);

app.use(compression());

app.use(cookieParser());

app.use(morgan('dev'));

app.use(bodyParser.json());

var path = require('path');`

**Comment by alansouzati** [comment]
thanks for reporting that. would you be willing to submit a pull request for that?

**Comment by epilande** [comment]
https://github.com/grommet/grommet-ferret/pull/26
