### ISSUE TITLE
App is not working - well it has several issues

### ISSUE THREAD

**Issue by genyded** [grommet/grommet-ferret#29]
This has been working fine, then yesterday the Nav sidebar, check boxes from the filter and several other areas stopped working. You can click them all day but nothing happens. Also in places like the enclosure screen the content bleeds through the header when scrolling (see screenshot). We using this as a reference foundation since the Grommet docs are not great and are lacking integration examples, so it would be nice if it could get fixed.

<details>
<summary>Screenshot of screen bleed</summary>
![image](https://cloud.githubusercontent.com/assets/3081676/15360136/06549566-1cd2-11e6-9a35-4c5b32d0d6e0.png)
</details>

**Comment by alansouzati** [comment]
hi @genyded I've just tried in my local machine and I cannot reproduce this issue. Can you please delete your `node_modules` and run npm install again ?

**Comment by genyded** [comment]
I am running it from [here](http://ferret.grommet.io/dashboard), so tehcnically there is not an install or node_modules. I do have the stable branch of Grommet installed locally, but this should be using whatever is installed on the ferret.grommet.io server (I hope). I have tried a few different browsers and systems and they all behave the same. If needed I can clone the repo and try that, but would prefer to just run it off the server.

**Comment by alansouzati** [comment]
I'm sorry I misunderstood your issue. Let me update ferret in the production server, thanks for catching that.

**Comment by alansouzati** [comment]
ferret.grommet.io is back in a working state. 

Also we are in the works for the new site with better documentation around patterns, templates and sample apps.

**Comment by genyded** [comment]
Fantastic! Been able to figure most stuff out using Ferret's source, but still fuzzy on Index, responsive, and layouts (box vs the box based components, Layer vs Split/Sidebar, etc). With each page we make things are coming clear though. Thanks so much and keep up the great work.

**Comment by alansouzati** [comment]
we have docs for grommet index. http://index.grommet.io

**Comment by genyded** [comment]
Yes - found them last might and slowly working our way through them - thanks again.
