### ISSUE TITLE
The animation doesn't work on IE11

### ISSUE THREAD

**Issue by christinJiang** [grommet/grommet-ferret#31]
Below animation doesn't work on IE11.
grommet-ferret/src/index.html

**Comment by epilande** [comment]
IE11 does not support SVG animations with CSS. Currently we're animating the paths using CSS & `stroke-dashoffset`, a possible solution would be to use JavaScript to animate the SVG paths.

**Comment by alansouzati** [comment]
I believe we will live with the lack of animation in the loading page for IE11. Thanks for your issue
