### ISSUE TITLE
Logo icon missing, unable to reopen sidebar

### ISSUE THREAD

**Issue by epilande** [grommet/grommet-ferret#32]
With the logo icon missing, there's nothing to click to reopen the sidebar.

![image](https://cloud.githubusercontent.com/assets/3210082/16695439/990067e2-44db-11e6-89c0-37e73f9157c4.png)
![image](https://cloud.githubusercontent.com/assets/3210082/16695443/9d140e06-44db-11e6-85b9-cb58feb662db.png)

**Comment by jwijay** [comment]
PR pending: https://github.com/grommet/grommet-ferret/pull/33

**Comment by alansouzati** [comment]
fixed
