### ISSUE TITLE
Opening the sidebar splits the application vertically in mobile view

### ISSUE THREAD

**Issue by isuru88** [grommet/grommet-ferret#34]
Please check the screenshots, 

1) Before opening the sidebar, 
![1](https://cloud.githubusercontent.com/assets/3070411/17179112/a433a4ee-5435-11e6-9353-3e33b07255f9.PNG)

2) After opening the sidebar
![2](https://cloud.githubusercontent.com/assets/3070411/17179114/a560b686-5435-11e6-8ad8-b8fa2e84fe19.PNG)

3) After scrolling down
![3](https://cloud.githubusercontent.com/assets/3070411/17179117/a6db0db8-5435-11e6-9eb9-46c72015e35e.PNG)

**Comment by alansouzati** [comment]
This is fixed in the latest ferret
