### ISSUE TITLE
Filter expands the whole window

### ISSUE THREAD

**Issue by epilande** [grommet/grommet-ferret#36]
![filter-display](https://cloud.githubusercontent.com/assets/3210082/17501251/c04abb08-5d78-11e6-9927-883a8d215437.gif)

**Comment by alansouzati** [comment]
Yeah. I've noticed this as well. would you be willing to create a pull request for this?

**Comment by epilande** [comment]
Hmm.. I can't seem to reproduce the issue locally. I've tried a clean install, latest release (`v0.6.10` & `v0.4.4`), & also alias build but no luck 😕  any ideas?

**Comment by alansouzati** [comment]
let me check locally as well. i think we just need to trigger a new CI/CD build for ferret.

**Comment by alansouzati** [comment]
Correct with the latest grommet stable this does not happen anymore. i've updated ferret and it looks ok now.
