### ISSUE TITLE
ERROR in ./~/grommet/~/css-loader!./~/grommet/~/sass-loader

### ISSUE THREAD

**Issue by arunmvit** [grommet/grommet-ferret#37]
cloned from https://github.com/grommet/grommet-ferret.git,

ran `npm install` at Grommet root folder as well (/usr/lib/node_modules/grommet  and ./grommet-ferret/node_modules/grommet) .

```
$ cd server
$ gulp dev
```

and from other terminal i started grommet-ferret# `gulp dev`

and getting 
ERROR in ./src/js/components/SessionMenu.js
Module not found: Error: Cannot resolve module 'react-gravatar' in /root/arungm/grommet-ferret/src/js/components
 @ ./src/js/components/SessionMenu.js 27:21-46

ERROR in ./~/grommet/~/css-loader!./~/grommet/~/sass-loader?outputStyle=expanded&includePaths[]=%2Froot%2Farungm%2Fgrommet-ferret%2Fnode_modules&includePaths[]=%2Froot%2Farungm%2Fgrommet-ferret%2Fnode_modules%2Fgrommet%2Fnode_modules!./src/scss/index.scss
Module build failed:
      @include inuit-font-size($label-font-size);
                              ^
      Undefined variable: "$label-font-size".
      in /root/arungm/grommet-ferret/node_modules/grommet-index/scss/grommet-index/_objects.index.scss (line 20, column 32)
 @ ./src/scss/index.scss 4:14-338 13:2-17:4 14:20-344

`i'm using :14.04.1-Ubuntu x86_64`

**Comment by alansouzati** [comment]
This is fixed in the latest ferret
