### ISSUE TITLE
Create updated example app and deprecate Ferret

### ISSUE THREAD

**Issue by ericsoderberghp** [grommet/grommet-ferret#39]

**Comment by svnlto** [comment]
As somebody that's used Ferret as a reference I'd like to know why it's going to be deprecated. Anything wrong with it?

**Comment by alansouzati** [comment]
Patterns need to be updated. Ferret is temporally deprecated while we work on updating the app with the new stuff we are working on. 

We will keep the name but upload an updated example that is closer to this: http://hc380.grommet.io

**Comment by svnlto** [comment]
Looking good, I'll look out for the update then.

**Comment by alansouzati** [comment]
Ferret has been updated
