### ISSUE TITLE
localhost:8010 is a logo?

### ISSUE THREAD

**Issue by DonRichards** [grommet/grommet-ferret#4]
All I get from 
http://localhost:8010/  OR  http://localhost:8010/rest is the logo. 

Is this suppose to happen?

**Comment by bryanjacquot** [comment]
Sounds like maybe you didn't start the backend server?  You'll have two `gulp dev` tasks running; one for the backend REST API server with mock data, one for the UI hot deployment server.

**Comment by alansouzati** [comment]
yup, port `8010` is for the REST API and there is no UI on that one.

If you run `gulp dev` inside grommet-ferret a browser window should open automatically at `localhost:8001`.

If you want to see how grommet-ferret would behave in real production server you need to run `gulp dist` and then `node server/server.js` to start a production server at `localhost:8010`.

**Comment by DonRichards** [comment]
I did. Had both running. It required both to run or neither would display anything. I'm starting to think it may be a dependency issue. I'm looking into it now.

**Comment by bryanjacquot** [comment]
@DonRichards were you able to get this working?

**Comment by bryanjacquot** [comment]
Closing for now.  Let us know if you still need assistance.
