### ISSUE TITLE
README.md: invalid link to Getting Started

### ISSUE THREAD

**Issue by iblazhko** [grommet/grommet-ferret#44]
Link "Modular Grommet" in README.md (section "How To", L11) points to a non-existing resource.

Currently, it is 

    http://grommet.io/docs/develop/get-started

Looks like it should be

    http://grommet.io/docs/get-started

or, perhaps

    http://grommet.io/docs/architecture

**Comment by cherih** [comment]
Updated the link in the README.md file to point to the current grommet-docs Get Started page.
