### ISSUE TITLE
IE11 hangs after being initialized

### ISSUE THREAD

**Issue by cherih** [grommet/grommet-ferret#46]
After starting the dev server, browse to the ferret app. It indicates that it is being initialized.  Once it is initialized, the Settings page is displayed. Press Submit to display the configuration page (see screenshot below).

This page stays on 0% and never gets updated.

![ie11_startup_issue](https://user-images.githubusercontent.com/25066338/32397126-e5b22158-c0ad-11e7-9661-81a8b72f31c6.PNG)

ferret will start up correctly if you browse to the app using chrome. Once the app has been configured in chrome, you can successfully browse to it using IE11 as well.

**Comment by alansouzati** [comment]
Fixed by https://github.com/grommet/grommet-ferret/commit/69c8a33f7030634968913264af9f8a977c942fae
