### ISSUE TITLE
Do we have a example about how to use Localization?

### ISSUE THREAD

**Issue by level5** [grommet/grommet-ferret#7]
I want to know how to use localization in component. 

it works with `FormattedMessage` in react-intl? is it the right way in grommet?
```jsx
<FormattedMessage
     id="Ferret"
     defaultMessage="Ferret"
/>
```

Thanks!

**Comment by alansouzati** [comment]
Yes, grommet uses react-intl for i18n. Your code looks right to me.

**Comment by level5** [comment]
Thanks!
